// static user obj for out of office use
export const user = {
  id: "1076",
  name: "Arhon Pineda",
  first: "Arhon",
  last: "Pineda",
  number: "5352",
  perm: "0",
  email: "apineda@haydenindustrial.com",
  position: "Software Developer",
  location: "Tulsa",
  id_manager: null,
  phone: "918-906-2551",
  carrier: "",
  password: "80082d10d0430452b2f971426acf0bdf",
  phone2: "",
  ext: "",
  fax: "",
  deleted: "-1",
  notify: "-1",
  jobstate: "-1",
  glovia: "-1",
  smslist: "-1",
  phonelist: "1",
  applist: "1",
  loglist: "1",
  wagerate: "0.00",
  ot_exempt: "-1",
  nipos_budget: null,
  capex_budget: null,
  internal: "-1",
  priv_login: "1",
  priv_users: "1",
  priv_effectivetime: "1",
  priv_qc: "1",
  priv_production: "1",
  priv_schedules: "2",
  priv_events: "1",
  priv_billing: "1",
  priv_materials: "1",
  priv_sales: "2",
  priv_financials: "1",
  priv_admin: "1",
  priv_docs: "-1",
  priv_cms: "-1",
  priv_projects: "-1",
  priv_formscreate: "1",
  groups: [
    "System Developers",
    "Quality",
    "Users",
    "Managers",
    "Production",
    "All Users",
    "HTI TX",
    "Injury Report and Investigation",
    "Assembly Team Leads",
    "Engineering",
    "Picklists: Handlers",
    "Picklists: Production",
    "Hourly Employees",
    "Hourly Employees Manager",
    "Inspection and Test Plan",
    "Designers",
    "Materials Purchasing",
    "Purchasing",
    "IT",
    "Maintenance",
    "Safety",
    "Operations",
    "Flushing",
    "Welding",
    "Lacing",
    "Coring",
    "Leak Test",
    "Braze",
    "Assembly",
    "Eng Sales",
    "Warehouse Material Control",
    "Human Resources",
    "Quality Control",
    "ICEC",
    "NIPO Users",
    "Buyers",
    "Developers",
    "Forklift Certified",
    "Manifest Workers",
    "OSHA Safety",
    "Project Managers",
    "Purchase Order Status",
    "Audits",
    "Planning Team",
    "Customer Service",
    "NCR Users",
    "ITP: Quality Team",
    "ITP: Engineering Team",
    "ITP: Production Team",
    "CRM General",
    "CRM Design",
    "CRM Technical",
    "CRM Supply",
    "CRM Legal",
    "CRM Engineering",
    "CRM Credit",
    "CRM Operations",
    "CAPEX Users",
    "CAPA Users",
    "EHS Inspections",
    "HR Comms HR",
    "HR Comms Supervisors",
    "HR Comms System",
    "CAPEX Buyers"
  ]
}